# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: dbyll
google_analytics: Nathan

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Nathan's Blog

description: Stylish Jekyll Theme
author:
  name: Nathan
  email: nathan.higgins@challoners.org
  github: RedBear17
  twitter: dbtek
  pinterest: asd123
  linkedin: asd123
  bio: Amazing
  email_md5: nathan.higgins@challoners.org

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
